

```{r}
library(rtracklayer)
```


```{r}
data <- read.delim2("~/Documents/KCL/research_project/orthofinder_res/dbs_blast/Results_Jun10/Orthogroups.txt", sep = ":", header = FALSE)
data
```


```{r}
v <- c()
ortho <- c()
for(i in 1:length(data$V1)){
  v <- unlist(strsplit(toString(data[i,2]), " "))
  v <- v[2:length(v)]
  
  if((length(grep("Sc4wPfr", v)) != 0) && (length(grep("FBpp", v)) != 0) && (length(grep("GENSCAN", v)) != 0)){
    ortho <- c(ortho, i)
  }
}

length(ortho)
head(ortho)
tail(ortho)
```


```{r}
orthogroups_union <- data[ortho,1]
length(orthogroups_union)

prot <- unlist(strsplit(toString(data[ortho,2]), " "))
prot <- prot[2:length(prot)]
length(prot)
length(unique(prot))

head(prot)
head(orthogroups_union)
```


```{r}
hy_gff <- readGFF("~/Documents/KCL/research_project/MEME_FIMO/Re__project_-_proteins_w__promoter_consensus_seq/hydra.gff")
dm_gff <- readGFF("~/Documents/KCL/research_project/MEME_FIMO/Re__project_-_proteins_w__promoter_consensus_seq/dmel.gff")
hs_gff <- readGFF("~/Documents/KCL/research_project/MEME_FIMO/Re__project_-_proteins_w__promoter_consensus_seq/hsap.gff")
```


```{r}
prot <- gsub(".t1", "", prot)
length(prot)
length(unique(prot))
prot <- unique(prot)
```


```{r}
hy <- which(prot %in% hy_gff$seqid)
length(hy)
dm <- which(prot %in% dm_gff$seqid)
length(dm)
hs <- which(prot %in% hs_gff$seqid)
length(hs)

length(hy) + length(dm) + length(hs)
```


```{r}
write(prot[hy], "hy_prot.txt")
write(prot[dm], "dm_prot.txt")
write(prot[hs], "hs_prot.txt")
```


```{r}
#orthogroups_union
head(data[orthogroups_union,])
prot_per_OG <- c()

for(i in 1:length(orthogroups_union)){
  prot_per_OG <- c(prot_per_OG, (unlist(strsplit(toString(data[orthogroups_union[i],2]), " "))[2]))
}

length(orthogroups_union)
length(prot_per_OG)
```



```{r}
write(prot_per_OG, "dmel_one_prot_per_OG")
```


```{r}
prot_per_OG <- c()
v <- c()

head(data[orthogroups_union,])

for(i in 1:length(orthogroups_union)){
  v <- unlist(strsplit(toString(data[orthogroups_union[i],2]), " "))
  prot_per_OG <- c(prot_per_OG, v[grep("GENSCAN", v)][1])
}
  
length(prot_per_OG)
```


```{r}
write(prot_per_OG, "hsap_one_prot_per_OG")
```





```{r}
hydra <- read.delim2("../prediction/hydra_pattern.txt", header = FALSE)
dmel <- read.delim2("../prediction/dmel_pattern.txt", header = FALSE)
hsap <- read.delim2("../prediction/hsap_pattern.txt", header = FALSE)

genes <- c()
for (i in 1:(length(hydra$V1)-1)){
  genes <- c(genes, strsplit(levels(hydra$V1)[2:length(hydra$V1)], " ")[[i]][1])
}

for (i in 1:(length(dmel$V1)-1)){
  genes <- c(genes, strsplit(levels(dmel$V1)[2:length(dmel$V1)], " ")[[i]][1])
}

for (i in 1:(length(hsap$V1)-1)){
  genes <- c(genes, strsplit(levels(hsap$V1)[2:length(hsap$V1)], " ")[[i]][1])
}

genes
```


```{r}
prot[which(prot %in% genes)]
write(prot[which(prot %in% genes)], "exactMatch.txt")
```


